kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: a-simple-pipeline
spec:
  params:
    - name: username
      type: string
  steps:
    - args:
      - hello
      - $(params.username)
      command:
      - echo
      computeResources: {}
      image: alpine:3
      name: say-hello
