apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: greeting-pipeline
spec:
  tasks:
    - name: print-greeting
      taskSpec:
        steps:
          - name: echo
            image: ubuntu
            script: |
              #!/usr/bin/env bash
              echo "Resolver working!"
